### ISSUE TITLE
What would be the command needed to increase the number of CPU cores destinated to EzAAI execution?

### ISSUE THREAD

**Issue by agg437** [lebsnu/ezaai#5]
Hello EzAAI team,

In your publication you talk about how speed execution is increased when using 30 CPU cores, what would be the option to implement that CPU usage?
PS: Great work with the pipeline, it is amazing!
Best regards,
Ana

**Comment by endix1029** [comment]
Hello,
Thank you for using our program!

The EzAAI `calculate` module can be boosted up using multiple cores by running it with `-t` option.

An example code would be:
`java -jar EzAAI.jar calculate -i db/ -j db/ -t 30 -o result.tsv`

Unfortunately, `extract` module cannot be run with multiple cores, since the dependent program `prodigal` does not support multi-threading options. Nevertheless, you can still boost up your progress by running multiple `extract` module runs simultaneously cuz they only consume single thread resources.

Thanks!

**Comment by agg437** [comment]
Perfect! that was what I was looking for!
Thanks!
